spring:
  application:
    name: say-hi-app
  cloud:
    stream:
      bindings:
        sayHi-in-0:
          group: say-hi-app
          destination: input-test
        sayHi-out-0:
          destination: output-test
  threads:
    virtual:
      enabled: true
