logging:
  level:
    root: info
    org.apache: warn
    io.confluent: warn

spring:
  application:
    name: poc
  cloud:
    stream:
      bindings:
        greet-in-0:
          group: ${spring.application.name}
          consumer:
            use-native-decoding: true
        greet-out-0:
          producer:
            use-native-encoding: true
      kafka:
        binder:
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            specific.avro.reader: true
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
          configuration:
            auto.register.schemas: false
            sasl.jaas.config: ${jaas.login.module} required username='${kafka.broker.user}' password='${kafka.broker.password}';
          auto-create-topics: false
        bindings:
          greet-in-0:
            consumer:
              destination-is-pattern: true
              reactive-auto-commit: true
              standard-headers: both
