logging:
  level:
    root: info
    org.apache: warn
    io.confluent: warn

spring:
  application:
    name: greeter
  cloud:
    stream:
      bindings:
        greet-in-0:
          group: greeter
          consumer:
            use-native-decoding: true
        greet-out-0:
          producer:
            use-native-encoding: true
      kafka:
        binder:
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            specific.avro.reader: true
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        bindings:
          greet-in-0:
            consumer:
              destination-is-pattern: true
              reactive-auto-commit: true
