name: "Apply infrastructure"

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**
      - .github/workflows/apply-infrastructure.yml

jobs:
  terraform:
    name: "Run Terraform"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.0
        id: plan-upload
        with:
          token: ${{ secrets.TF_API_TOKEN }}
          organization: ${{ vars.TF_CLOUD_ORGANIZATION }}
          workspace: ${{ vars.TF_WORKSPACE }}

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.0
        id: apply-run
        with:
          token: ${{ secrets.TF_API_TOKEN }}
          organization: ${{ vars.TF_CLOUD_ORGANIZATION }}
          workspace: ${{ vars.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.0
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          token: ${{ secrets.TF_API_TOKEN }}
          organization: ${{ vars.TF_CLOUD_ORGANIZATION }}
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"

      - name: Get output
        uses: hashicorp/tfc-workflows-github/actions/workspace-output@v1.3.0
        id: output
        with:
          token: ${{ secrets.TF_API_TOKEN }}
          organization: ${{ vars.TF_CLOUD_ORGANIZATION }}
          workspace: ${{ vars.TF_WORKSPACE }}
