name: "Build infrastructure"

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**
      - .github/workflows/build-infrastructure.yml

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  CONFLUENT_CLOUD_API_SECRET: "${{ secrets.CONFLUENT_CLOUD_API_SECRET }}"

defaults:
  run:
    working-directory: ./infrastructure

jobs:
  terraform:
    name: "Run Terraform"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: plan-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
