name: Build Code

on:
  push:
    branches:
      - main
    paths:
      - code/**
      - .github/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - code/**
      - .github/**

defaults:
  run:
    working-directory: ./code

permissions:
  pull-requests: read
  contents: read
  security-events: write

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build & Run unit tests
        run: ./mvnw -B clean test -PnativeTest
      - name: Run SonarCloud analysis
        run: ./mvnw -B sonar:sonar -Dsonar.projectKey=tamamico_poc-spring-cloud-stream-native-code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Run Snyk analysis
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-code.sarif
      - name: Upload result to GitHub Code Scanning (source code)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: /home/runner/work/poc-spring-cloud-stream-native/poc-spring-cloud-stream-native/code/snyk-code.sarif
          category: source-code
      - name: Build Docker image
        run: ./mvnw -B clean spring-boot:build-image -Pnative
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: docker.io/library/poc-scs-native:0.0.1-SNAPSHOT
          args: --sarif-file-output=snyk-docker.sarif
      - name: Upload result to GitHub Code Scanning (Docker image)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-docker.sarif
          category: docker
