name: Build Code

on:
  push:
    branches:
      - main
    paths:
      - code/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - code/**

defaults:
  run:
    working-directory: ./code

permissions:
  pull-requests: read
  contents: read

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build & Run unit tests
        run: ./mvnw -B clean test -PnativeTest
      - name: Run SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -B sonar:sonar -Dsonar.projectKey=tamamico_poc-spring-cloud-stream-native-code
      - name: Set-up Snyk CLI
        uses: snyk/actions/setup@0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Code test
        run: snyk code test --sarif > snyk-code.sarif
      - name: Snyk Open Source monitor
        run: snyk monitor --all-projects
      - name: Build Docker image
        run: ./mvnw -B clean spring-boot:build-image -Pnative
      - name: Snyk Container monitor
        run: snyk container monitor scs-native
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif
