name: Build Code

on:
  push:
    branches:
      - dependabot/**
    paths:
      - code/**
      - .github/workflows/**

permissions:
  pull-requests: read
  contents: read
  security-events: write

jobs:
  build-source-code:
    name: Build source code
    uses: ./.github/workflows/build-code.yml
    secrets: inherit
