name: Build Code

on:
  push:
    branches:
      - main
    paths:
      - 'code/**'
      - '.github/workflows/**-code.yml'
      - '.github/workflows/build-docker.yml'
      - '!.github/workflows/dependabot-code.yml'

permissions:
  contents: read
  pull-requests: read
  security-events: write
  packages: write

jobs:
  build-source-code:
    name: Build source code
    uses: ./.github/workflows/build-code.yml
    secrets: inherit
  build-application-deliverable:
    needs: build-source-code
    name: Build application deliverable
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
  clean-old-maven-artifacts:
    needs: build-source-code
    name: Clean up old Maven artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'es.ecristobal.poc-scs-native'
          package-type: 'maven'
          min-versions-to-keep: 2
  clean-old-docker-images:
    needs: build-application-deliverable
    name: Clean up old Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'poc-scs-native'
          package-type: 'container'
          min-versions-to-keep: 2
