name: Build Code

on:
  push:
    branches:
      - main
    paths:
      - code/**
      - .github/**

permissions:
  pull-requests: read
  contents: read
  security-events: write

jobs:
  build-source-code:
    name: Build source code
    uses: ./.github/workflows/build-code.yml
    secrets: inherit
  build-application-deliverable:
    needs: build-code
    name: Build application deliverable
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
