name: Build Code

on:
  push:
    branches:
      - main
    paths:
      - 'code/**'
      - '.github/workflows/**-code.yml'
      - '.github/workflows/build-docker.yml'
      - '!.github/workflows/dependabot-code.yml'

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  build-source-code:
    name: Build source code
    uses: ./.github/workflows/build-code.yml
    secrets: inherit
  build-application-deliverable:
    needs: build-source-code
    name: Build application deliverable
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
